version: '3'

services:
  postgres:
    image: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nucleoid
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_DB: nucleoid
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
