name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: target/**
          key: ${{ matrix.os }}-cargo
      - name: Install rust toolchain
        run: rustup update stable && rustup default stable
      - name: Build with cargo
        run: cargo build --verbose --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nucleoid-backend
          path: target/release/nucleoid-backend
