name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: target/**
          key: ${{ matrix.os }}-cargo
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build with cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nucleoid-backend
          path: target/release/nucleoid-backend
